### ISSUE TITLE
Node Override does not work

### ISSUE THREAD

**Issue by raandree** [gaelcolas/DscInfraSample#17]
The SRV02 in DEV defines

```
Shared1:
  DestinationPath: C:\MyRoleParam.txt
  Param1: This is the Node override!
```

However the MOF files and also RSOP still have the value as defined in WindowsBase.yml

```
Shared1:
  DestinationPath: C:\MyRoleParam.txt
  Param1: This is the Role Value!
```

Are the lookup options for the value incorrect? I have tried 'hash' and 'deep', both did not work.

**Comment by raandree** [comment]
Actually it works but the sample data is not complete causing the override settings to be ignored. Now I also understand something we have talked about some time ago about putting nodes into folders.

**Comment by gaelcolas** [comment]
For further info on this as someone asked again, the problem in this example lies in the fact that `$Node.Environment` is not set to 'DEV', which means the lookup by ResolutionPrecedence `'AllNodes\$($Node.Environment)\$($Node.Name)'` returns `$null`.

In our example the value for `$Node.Environment` should be set by the name of the Parent folder of the Node file, but this is specific of our layout, and I haven't found an elegant way to define this yet in Datum. (How to tell Datum that The parent folder of `SRV02.yml` is the property `Environment`).

The alternative for now is to either:
- Customize the way the Config Data is Loaded into `$ConfigurationData.AllNodes`
- Re-Define the key/values in the object definition (in this case adding `Environment: DEV` to the `SRV02.yml` file)
