### ISSUE TITLE
.build.ps1 -resolveDependency  false start (PSVersion 5.1.17134.137)

### ISSUE THREAD

**Issue by sundmoon** [gaelcolas/DscInfraSample#19]
I think it is because of
https://github.com/PowerShell/PowerShell/issues/7209

Staying at Windows Powershell, what should I do to overcome it right now? 

===============================================================================
                        COMPILE ROOT CONFIGURATION

-------------------------------------------------------------------------------
  /./Compile_Root_Configuration
  C:\DEV\DscInfraSample\.build\DSC\ConfigData.Build.ps1:91

PSDesiredStateConfiguration\Configuration : The term 'Set-PSTopConfigurationName' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At C:\DEV\DscInfraSample\RootConfiguration.ps1:7 char:1
+ configuration "RootConfiguration"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-PSTopConfigurationName:String) [Configuration], ParentContainsError
   RecordException
    + FullyQualifiedErrorId : CommandNotFoundException,Configuration

ERROR OCCURED DURING COMPILATION: Compilation errors occurred while processing configuration 'RootConfiguration'. Please review the errors reported in error stream and modify your configuration code appropriately.
Compilation errors occurred while processing configuration 'RootConfiguration'. Please review the errors reported in
error stream and modify your configuration code appropriately.
At
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917
char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (RootConfiguration:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration

PSDesiredStateConfiguration\Configuration : The term 'Set-PSTopConfigurationName' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At C:\DEV\DscInfraSample\RootConfiguration.ps1:7 char:1
+ configuration "RootConfiguration"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-PSTopConfigurationName:String) [Configuration], ParentContainsError
   RecordException
    + FullyQualifiedErrorId : CommandNotFoundException,Configuration

Exception calling "InvokeWithContext" with "2" argument(s): "The term 'Set-PSTopConfigurationName' is not recognized
as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again."
At
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2232
char:13
+             $result = $Body.InvokeWithContext($functionsToDefine, $va ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by gaelcolas** [comment]
Just comment out that line for now, It's a nice to have to 'tag' the MOF
but not used in this repo.

When I can I'll test this as there must be a way to do this, otherwise
there's other ways to tag the MOF.

Gael

**Comment by sundmoon** [comment]
and with PS Core I see another problem: the build task can't load Datum (that manually loads)

===============================================================================
                        TEST CONFIGDATA

-------------------------------------------------------------------------------
  /./Test_ConfigData
  C:\DEV\DscInfraSample\.Build.ps1:259

Executing all tests in 'C:\DEV\DscInfraSample\Tests'

Executing script C:\DEV\DscInfraSample\Tests\01 ConfigData\ConfigData.Tests.ps1
  [-] Error occurred in test script 'C:\DEV\DscInfraSample\Tests\01 ConfigData\ConfigData.Tests.ps1' 83ms
    CommandNotFoundException: The 'New-DatumStructure' command was found in the module 'datum', but the module could not be loaded. For more information, run 'Import-Module datum'.
    at <ScriptBlock>, C:\DEV\DscInfraSample\Tests\01 ConfigData\ConfigData.Tests.ps1: line 7
    at <ScriptBlock>, C:\DEV\DscInfraSample\BuildOutput\Modules\Pester\4.3.1\Pester.psm1: line 837
    at Invoke-Pester<End>, C:\DEV\DscInfraSample\BuildOutput\Modules\Pester\4.3.1\Pester.psm1: line 852
    at <ScriptBlock>, C:\DEV\DscInfraSample\.Build.ps1: line 270
    at *Task, C:\DEV\DscInfraSample\BuildOutput\Modules\InvokeBuild\5.4.1\Invoke-Build.ps1: line 526
    at *Task, C:\DEV\DscInfraSample\BuildOutput\Modules\InvokeBuild\5.4.1\Invoke-Build.ps1: line 503
    at <ScriptBlock><End>, C:\DEV\DscInfraSample\BuildOutput\Modules\InvokeBuild\5.4.1\Invoke-Build.ps1: line 684
    at <ScriptBlock>, C:\DEV\DscInfraSample\.Build.ps1: line 149
Tests completed in 83ms
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
ERROR: Assertion failed.
At C:\DEV\DscInfraSample\.Build.ps1:272 char:5
+     assert ($testResults.FailedCount -eq 0)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\DEV\DscInfraSample\.Build.ps1:259 char:1
+ task Test_ConfigData {
+ ~~~~~~~~~~~~~~~~~~~~~~
At C:\DEV\DscInfraSample\.Build.ps1:204 char:5
+     task . Clean_BuildOutput,
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 7 tasks, 1 errors, 0 warnings 00:00:04.0106096
Assertion failed.
At C:\DEV\DscInfraSample\.Build.ps1:272 char:5
+     assert ($testResults.FailedCount -eq 0)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Assert-Build], Exception
    + FullyQualifiedErrorId : Assert-Build
PS C:\DEV\DscInfraSample> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\DEV\DscInfraSample> ipmo datum -Verbose
VERBOSE: Loading module from path 'C:\DEV\DscInfraSample\BuildOutput\Modules\datum\0.0.32\datum.psd1'.
VERBOSE: Populating RepositorySourceLocation property for module datum.
VERBOSE: Loading module from path 'C:\DEV\DscInfraSample\BuildOutput\Modules\datum\0.0.32\Sc

**Comment by SimonWahlin** [comment]
I did some digging on this problem. I'm running Windows 10 with WindowsPowerShell 5.1 and I have the module PSDesiredStateConfiguration with version 1.1 in the path:  

`C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration`

The module manifest does not specify any RootModule, PSDesiredStateConfiguration.psm1 is listed with NestedModules. This means that the command Set-PSTopConfigurationName is not available inside the module but inside a module inside the module (did that make sense?).

On PowerShell Core (6.1.0-preview.2) on the other hand, the module PSDesiredStateConfiguration only contains a psm1 file and no manifest so here we don't get into trouble with nested modules.

### Anyhow, I can see two solutions:

1. The command Set-PSTopConfigurationName just sets the value of a variable in the module scope, read and write directly to the variable instead of calling the commands like this:  
`& $module {param($tag,$Env) $Script:PSTopConfigurationName = "MOF_$($Env)_$($tag)"} "$BuildVersion",$Environment`
This should work in both Windows PowerShell and PowerShell Core (tested on 6.1.0-preview.2)

1. Call the function inside the nested module, like this:  
`& $module {param($Value)$nestedModule = gmo PSDesiredStateConfiguration | ? ModuleType -eq 'Script';& $nestedModule {param($value)Set-PSTopConfigurationName $Value} $Value} 'Testing'`
This only works in Windows PowerShell.

I'd recommend the first method and would be happy to submit a PR if interested.

**Comment by gaelcolas** [comment]
This is makes sense, very good find @SimonWahlin thank you.
Your Solution 1 (and PR #20) look good, I'll merge shortly.
