### ISSUE TITLE
Get-DSCSplattedResource with Multiple Resource Instances

### ISSUE THREAD

**Issue by garron-rlg** [gaelcolas/DscInfraSample#24]
https://github.com/gaelcolas/DscInfraSample/blob/9df38c608dc1d7229621884ed648696e48617625/RootConfiguration.ps1#L22

@gaelcolas can I check my understanding of how this works please? 

If using Datum, there is a use case where configurations get merged for a node. In such a case, there might be multiple instances of a confiiguration for example where all nodes have an agent that runs as a service, then the role of the node added a service for the application. 

In the line, I've referenced above, Get-DSCSplattedResource, would use the Configruation name "Service" as the resourceID when the MOF is created. In such cases, where there are multiple instanced the MOF would fail to compile since you may only have a since resourceID of "Service" Is my understanding here correct? 

If my understanding here is correct, is the correct way to handle such situations to include another key in the properties described within the Datum tree, for example matching the "Title" and "Name" concept of Puppet?

**Comment by raandree** [comment]
You need to make sure that the ResourceID is always unique. The name is assigned to a config item in the configurations (composite resources).

A more comprehensive approach of using Datum is the [DscWorkshop](https://github.com/raandree/DscWorkshop). It uses the configurations published in [CommonTasks](https://github.com/AutomatedLab/CommonTasks).

For services, the ResourceId is generated [here](https://github.com/AutomatedLab/CommonTasks/blob/689950b09868fc0fa28299636655244d98299b9b/CommonTasks/DscResources/WindowsServices/WindowsServices.schema.psm1#L18). It is the 'ExecutionName' ```$service.Name```. While writing this I think that using just the service name may generate conflicts with other resources so it might be a good idea to change it to ```"xService_$($service.Name)"```.

So in our samples the ResourceId is not part of the config data but generated during compilation.

**Comment by gaelcolas** [comment]
What @raandree said ;)
Technically you can use resources directly, but using configuration (composites) is better, and avoid the key issue.

**Comment by garron-rlg** [comment]
Thanks - hadn't considered composites.
